version: "3.9"
services:
    mysql:
        image: mariadb:10.11.8
        # Uncomment below when on Mac M1
        # platform: linux/arm64/v8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: project
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306

    adminer:
        image: adminer   # Automaticky stáhne nejnovější verzi
        restart: always
        ports:
            - 8080:8080
